### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by papachoco** [NextThought/nti.property#4]
Jason,

It would be nice if nti.property.dataurl.encode/decode support [base64] gzip encoding; using the same protocol format.

Thanks

Carlos

**Comment by jamadden** [comment]
GZIP encoding is not part of [RFC 2397](https://tools.ietf.org/html/rfc2397) that specifies `data:` URLs. If we did that, they wouldn't be usable by browsers or other tools AFAICS.

Moreover, I'm not sure how useful that would be. The transport should already be compressed, so we wouldn't save anything there. The storage is definitely compressed, so we wouldn't save anything there. data URLs are usually used for images, which have their own compression, so it's unlikely that we'd actually get very much of a compression factor most of the time on any single value (note that the HTTP transport and storage are different cases because they have more data to work with).

**Comment by papachoco** [comment]
Awesome thx for the explanation
